version: '3'
services:
        web:
                image: cpt_v1
                build: .
                ports:
                        - "8064:8064"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
